site:
  title: Odoo Adapter for APPUiO Cloud
  start_page: appuio-odoo-adapter::index.adoc
  url: https://vshn.github.io/appuio-odoo-adapter
content:
  sources:
    - url: ../antora
      branches:
        - HEAD
        - docs/v*
      start_path: docs
ui:
  bundle:
    url: https://github.com/vshn/antora-ui-default/releases/download/2.0.15/ui-bundle.zip
    snapshot: true
output:
  dir: .public/
  clean: true
